### ISSUE TITLE
not exists tsd.config file

### ISSUE THREAD

**Issue by MarlonFan** [vilic/vio#7]
我知道我的英语绝逼是错的...

**Comment by vilic** [comment]
tsd.json, 为什么要它.

**Comment by MarlonFan** [comment]
你的typting里面有文件的呀...  我添加新的怎么维护

**Comment by vilic** [comment]
把这个当 module 用，你不用关心我的 typings 呀。另外自己的 typings 存仓库就好，不推荐 tsd.json 来维护。

**Comment by MarlonFan** [comment]
这样.  又小挫了一下- - 懂了- -
